# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

	boot.initrd.systemd = {
		initrdBin = with pkgs; [
			btrfs-progs
			coreutils
			util-linux
			findutils
		];
		services.prune-subvolumes = {
			# This service is required for boot to succeed
			requiredBy = [ "initrd.target" ];
			# Should complete before any file systems are mounted
			before = [ "sysroot.mount" ];
			after = [
				# Allow hibernation to resume before trying to alter any data
				"local-fs-pre.target"
				"initrd-root-device.target"
			];
			# Wait for the disk to appear
			requires = [ "initrd-root-device.target" ];
			# Specify dependencies explicitly
			unitConfig.DefaultDependencies = false;
			# The script needs to run to completion before this service is done
			serviceConfig = {
				Type = "oneshot";
				# also print to TTY
				StandardOutput = "journal+console";
				StandardError = "journal+console";
			};
			script = ''
				mkdir /btrfs_tmp
				mount /dev/disk/by-label/nixos /btrfs_tmp
				if [[ -e /btrfs_tmp/root ]]; then
					mkdir -p /btrfs_tmp/old_roots
					timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/root)" "+%Y-%m-%-d_%H:%M:%S")
					mv /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
				fi

				delete_subvolume_recursively() {
					IFS=$'\n'
					for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
						delete_subvolume_recursively "/btrfs_tmp/$i"
					done
					btrfs subvolume delete "$1"
				}

				for i in $(find /btrfs_tmp/old_roots/ -maxdepth 1 -mtime +30); do
					delete_subvolume_recursively "$i"
				done
			
				btrfs subvolume create /btrfs_tmp/root
				umount /btrfs_tmp
			'';
		};
	};

  fileSystems."/persistent" =
    { device = "/dev/disk/by-label/nixos";
      neededForBoot = true;
      fsType = "btrfs";
      options = [ "subvol=persistent" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
