{ self, inputs, ... }: {

  # This is your system configuration entry-point
  flake.nixosModules.myMachineHardware = 
    
  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  { config, lib, pkgs, modulesPath, ... }:

  {
    imports = [ ];

    boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/f868d59c-3f00-46e9-b265-ab589259d54a";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/E56B-EC94";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/831a582a-f183-4ba2-846b-bf85c07e5ecf"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };  
}
